title: kontinua IT consulting
author: keep on swimming
#email:
description: >
  CI/CD, kubernetes, Atlassian Consulting
baseurl: ""
url: "http://oiua.de"
twitter_username: kontinuaIT
github_username:  oiua

theme: minima
#theme: jekyll-theme-primer
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
